services:
  - type: web
    name: blogproject
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn blogproject.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: "3.11.7"

databases:
  - name: blogproject
    plan: free
    ipAllowList: []
